Update CONTIBUTING.md to reflect the two week public discussion period
sstsimulator/sst-core pull request #1047
Opened 2024-02-26 18:58 UTC by feldergast

2024-02-26 19:19 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1339</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1320</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1322</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 498</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 415</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 373</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 327</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 679</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 161</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (feldergast/sst-core)</dt>
  <ul>
    <li>Branch: contib-update</li>
    <li>SHA: 55cd5db297656a3f8b9796287212e85e75116512</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 69a32cbc43ea21c63d3a62f25a71697c0d39f686</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 9512fd8a6690fdce75ad7843c41731af051c6cc3</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0443cf578fcfd2fe8fe9ac3b039c3e16ba1f5892</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: feldergast
</details>
</details>

2024-02-26 20:35 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1339</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1320</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1322</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 498</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 415</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 373</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 327</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 679</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 161</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2024-02-26 20:35 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2024-02-26 20:35 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-27 00:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-27 05:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-27 09:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-27 13:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-27 17:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-27 21:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-28 02:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-28 06:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-28 10:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-28 14:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-28 18:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-28 23:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-29 03:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-29 07:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-29 12:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-02-29 16:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-01 01:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-01 05:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-01 09:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-01 13:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-01 16:07 UTC, gvoskuilen commented on CONTRIBUTING.md
> +Now you can branch from `devel` to create new features and when you push those feature branches they will push to your fork. When you pull devel, it will get updates from the official sst repo, avoid
Period at end of the sentence and maybe "avoiding the need to merge changes from the main repository into your local fork."

2024-03-01 16:10 UTC, gvoskuilen commented on CONTRIBUTING.md
> +SST is an open source project and we encourage contribution of new features. For new features, please open a “Feature Request” in the GitHub issues tracker and describe both the use-case and the prop
"If the feature can be implemented using one of the existing "plug-in" APIs in the core, ..." (currently says "existing" twice)

2024-03-01 16:17 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES!

2024-03-01 16:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-01 20:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-02 01:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-02 05:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-02 09:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-02 14:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-02 18:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-02 22:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-03 02:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-03 07:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-03 11:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-03 15:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-03 19:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-03 20:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-03-04 01:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-03-04 05:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-03-04 09:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-03-04 13:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-03-04 22:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-03-05 03:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-03-05 08:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-03-05 10:47 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection is Not Necessary for this Pull Request.

2024-03-05 10:53 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1341</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1322</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1324</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 500</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 417</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 375</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 329</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 681</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 163</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (feldergast/sst-core)</dt>
  <ul>
    <li>Branch: contib-update</li>
    <li>SHA: 9de3f56339029391249f4045dfd25902ebb7c8b5</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 69a32cbc43ea21c63d3a62f25a71697c0d39f686</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 9512fd8a6690fdce75ad7843c41731af051c6cc3</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0443cf578fcfd2fe8fe9ac3b039c3e16ba1f5892</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: feldergast
</details>
</details>

2024-03-05 11:17 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Error: Jenkins Jobs - Error: [Jenkins] Cannot retrieve build running status on build (FATAL: ERROR : [jwrap: build.is_running():793:/home/sstbuilder/buildtools/autotester/support/jenkins_support.py] - General Exception: (504 Server Error: Gateway Time-out for url: https://sst-jenkins.sandia.gov/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist/375/api/python?depth=1&tree=building))

2024-03-05 15:19 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1342</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1323</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1325</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 501</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 418</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 376</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 330</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 682</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 164</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (feldergast/sst-core)</dt>
  <ul>
    <li>Branch: contib-update</li>
    <li>SHA: 9de3f56339029391249f4045dfd25902ebb7c8b5</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 69a32cbc43ea21c63d3a62f25a71697c0d39f686</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 9512fd8a6690fdce75ad7843c41731af051c6cc3</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0443cf578fcfd2fe8fe9ac3b039c3e16ba1f5892</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: feldergast
</details>
</details>

2024-03-05 16:36 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1342</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1323</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1325</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 501</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 418</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 376</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 330</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 682</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 164</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2024-03-05 16:36 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2024-03-05 16:36 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-05 20:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-06 01:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-06 05:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-06 09:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-06 14:09 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-06 22:37 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-07 02:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-07 07:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-07 11:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-07 15:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-03-07 16:15 UTC, gvoskuilen approved these changes

2024-03-07 16:17 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ gvoskuilen ]!

2024-03-07 16:18 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - Forked Repos cannot Automerge

2024-03-07 20:47 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - Forked Repos cannot Automerge

2024-03-07 21:01 UTC, merged

2024-03-07 23:43 UTC, jpkenny requested changes
"twe week" -> "two week"