Initial checkpointing support
sstsimulator/sst-core pull request #1075
Opened 2024-05-09 15:21 UTC by feldergast

Initial checkpointing support

- Currently only supports serial runs
- Updates to serialization to support checkpointing
  - Added ability to turn on pointer tracking
  - Added ability to serialize non-pointer variables, but track address of data as a pointer.
- Changed templating for handlers to support checkpointing
  - Function pointer is now a non-type template parameter
- Added additional serialization tests and new checkpointing tests
- Added a function to ConfigBase so you could query whether or not an option was set on the command line.

Other incidental changes:

- Remove old references to SharedRegion
- Removed type checking in testing comparison filters.  This was done because the filter is called for every line of output and the type checks apparently aren't very efficient and were a performance bottleneck for tests with a lot of output
- Added Python Module output to sst-info
- Added fflush to all output in TraceFunction

2024-05-09 17:54 UTC, jmlapre submitted a review, later dismissed
Everything looks OK.  I would maybe add a comment here to make it clear that checkpointing is only supported within a single machine or at least not across two different architectures.

2024-05-09 18:48 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection is Not Necessary for this Pull Request.

2024-05-09 18:53 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1402</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1382</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1384</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 532</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 449</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 407</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 361</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 741</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 195</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (feldergast/sst-core)</dt>
  <ul>
    <li>Branch: checkpointing-serial</li>
    <li>SHA: 34727aaf0224b164b9064709b0ad21ff504d483d</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: d62858a7e10d5e30fd83571ecca643702efc7184</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 964ee7e921be563bf088e98b9238697472929ee8</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0443cf578fcfd2fe8fe9ac3b039c3e16ba1f5892</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: feldergast
</details>
</details>

2024-05-09 19:25 UTC, jmlapre submitted a review, later dismissed

2024-05-09 20:10 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1402</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1402/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1382</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1382/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1384</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2/1384/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 532</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore/532/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_bool_array</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_check</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_installcheck</td>
    <td>FAILED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 449</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core/449/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_bool_array</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_map</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_set</td>
    <td>FAILED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 407</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist/407/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 361</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core/361/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 741</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements/741/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 195</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore/195/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_sst_macro_make_check</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_installcheck</td>
    <td>FAILED</td>
  </tr>
</table>
</details>

2024-05-10 00:24 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1404</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1384</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1386</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 533</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 450</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 408</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 362</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 743</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 196</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (feldergast/sst-core)</dt>
  <ul>
    <li>Branch: checkpointing-serial</li>
    <li>SHA: 34727aaf0224b164b9064709b0ad21ff504d483d</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: d62858a7e10d5e30fd83571ecca643702efc7184</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 964ee7e921be563bf088e98b9238697472929ee8</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0443cf578fcfd2fe8fe9ac3b039c3e16ba1f5892</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: feldergast
</details>
</details>

2024-05-10 01:44 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1404</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1404/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1384</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1384/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1386</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2/1386/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 533</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore/533/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_bool_array</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_set</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_check</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_installcheck</td>
    <td>FAILED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 450</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core/450/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_bool_array</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_map</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_set</td>
    <td>FAILED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 408</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist/408/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_Module</td>
    <td>FAILED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 362</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core/362/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 743</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements/743/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 196</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore/196/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_sst_macro_make_check</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_installcheck</td>
    <td>FAILED</td>
  </tr>
</table>
</details>

2024-05-10 04:00 UTC, jpkenny requested changes
Found some typos and style complaints. No major technical issues that I see (it's a lot of code).

2024-05-10 05:54 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1407</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1387</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1389</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 534</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 451</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 409</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 363</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 746</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 197</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (feldergast/sst-core)</dt>
  <ul>
    <li>Branch: checkpointing-serial</li>
    <li>SHA: 34727aaf0224b164b9064709b0ad21ff504d483d</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: d62858a7e10d5e30fd83571ecca643702efc7184</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 4ca45f3abcc6b615bc8f8d630eecd153717073e3</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0443cf578fcfd2fe8fe9ac3b039c3e16ba1f5892</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: feldergast
</details>
</details>

2024-05-10 07:17 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1407</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1407/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1387</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1387/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1389</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2/1389/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 534</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore/534/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_bool_array</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_set</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_check</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_installcheck</td>
    <td>FAILED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 451</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core/451/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_array</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_set</td>
    <td>FAILED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 409</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist/409/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_Module</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_map</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_set</td>
    <td>FAILED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 363</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core/363/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 746</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements/746/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 197</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore/197/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_sst_macro_make_check</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_installcheck</td>
    <td>FAILED</td>
  </tr>
</table>
</details>

2024-05-10 11:23 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1408</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1388</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1390</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 535</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 452</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 410</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 364</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 747</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 198</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (feldergast/sst-core)</dt>
  <ul>
    <li>Branch: checkpointing-serial</li>
    <li>SHA: 34727aaf0224b164b9064709b0ad21ff504d483d</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: d62858a7e10d5e30fd83571ecca643702efc7184</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 4ca45f3abcc6b615bc8f8d630eecd153717073e3</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0443cf578fcfd2fe8fe9ac3b039c3e16ba1f5892</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: feldergast
</details>
</details>

2024-05-10 12:42 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1408</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1408/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_array</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_set</td>
    <td>FAILED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1388</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1388/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1390</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2/1390/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 535</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore/535/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_Module</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_bool_array</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_set</td>
    <td>PASSED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_check</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_installcheck</td>
    <td>FAILED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 452</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core/452/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_array</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_set</td>
    <td>FAILED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 410</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist/410/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint_Module</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_map</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_set</td>
    <td>PASSED</td>
  </tr>
</table>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 364</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core/364/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 747</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements/747/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 198</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore/198/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_sst_macro_make_check</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_sst_macro_make_installcheck</td>
    <td>FAILED</td>
  </tr>
</table>
</details>

2024-05-10 16:18 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection is Not Necessary for this Pull Request.

2024-05-10 16:24 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1409</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1389</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1391</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 536</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 453</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 411</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 365</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 748</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 199</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (feldergast/sst-core)</dt>
  <ul>
    <li>Branch: checkpointing-serial</li>
    <li>SHA: 0210218c9293100b4e0151c25a98ab0d3dd79533</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: d62858a7e10d5e30fd83571ecca643702efc7184</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 4ca45f3abcc6b615bc8f8d630eecd153717073e3</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0443cf578fcfd2fe8fe9ac3b039c3e16ba1f5892</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: feldergast
</details>
</details>

2024-05-10 16:34 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Error: Jenkins Jobs - A user has pushed a change to the PR before testing completed. NEW EVENT 'committed', ID C_kwDOApdhgNoAKDdkZjFhMmU3OWE2YjU4ZjE0YjkxZWEwZDQ0Y2NkZTQzMDU4M2Y3Y2E... The Jenkins Jobs will be shutdown; Testing of this PR must occur again.

2024-05-10 16:36 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1409</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1409/consoleFull</li>
<li>Job: - Status:     None</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1389</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1389/consoleFull</li>
<li>Job: - Status:     None</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1391</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2/1391/consoleFull</li>
<li>Job: - Status:     None</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 536</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore/536/consoleFull</li>
<li>Job: - Status:     None</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 453</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core/453/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 411</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist/411/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 365</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core/365/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 748</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements/748/consoleFull</li>
<li>Job: - Status:     None</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 199</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore/199/consoleFull</li>
<li>Job: - Status:     None</li>
</ul>
</details>

2024-05-10 16:48 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection is Not Necessary for this Pull Request.

2024-05-10 16:54 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1410</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1390</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1392</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 537</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 454</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 412</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 366</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 749</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 200</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (feldergast/sst-core)</dt>
  <ul>
    <li>Branch: checkpointing-serial</li>
    <li>SHA: 7df1a2e79a6b58f14b91ea0d44ccde430583f7ca</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: d62858a7e10d5e30fd83571ecca643702efc7184</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 4ca45f3abcc6b615bc8f8d630eecd153717073e3</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0443cf578fcfd2fe8fe9ac3b039c3e16ba1f5892</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: feldergast
</details>
</details>

2024-05-10 18:11 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 4 Hrs. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h2>

<ul>
  <li>Result: <b>PASSED</b></li>
  <li>Build #: 1410</li>
  <li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements/1410/consoleFull</li>
</ul>
<h2>Job: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h2>
<ul>
<li>Result: <b>FAILED</b></li>
<li>Build #: 1390</li>
<li>URL: Jenkins server at https://sst-jenkins.sandia.gov/view/SST/job/SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2/1390/consoleFull</li>
<li>Job: - Status:     FAILURE</li>
</ul>

<h3>Test Results</h3>
<table>
  <tr>
    <th>Test Name</th>
    <th>Status</th>
  </tr>

  <tr>
    <td>test_Checkpoint</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_Module</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_array</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_bool_array</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_map</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SharedObject_set</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SubComponent_sc_2a</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_SubComponent_sc_2u2u</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_sc_2u</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_sc_2u2a</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_sc_2ua</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_sc_2uu</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_sc_a</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_sc_u</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_sc_u2a</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_sc_u2u</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_sc_ua</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Checkpoint_sc_uu</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Ariel_test_snb</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_MemPool_overflow</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_Sirius_Zodiac_27</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_cacheTracer_2</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_json_io_parallel</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_python_io_parallel</td>
    <td>FAILED</td>
  </tr>

  <tr>
    <td>test_miranda_randomgen</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_miranda_singlestream</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_rdmaNic_short_tests_001_app_rdma_msg</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_rdmaNic_short_tests_002_app_mpi_IMB_MPI1</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_sstexternalelement_001</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_001_small_basic_io_lseek_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_002_small_basic_io_hello_world_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_003_small_basic_io_hello_world_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_004_small_basic_io_hello_world_cpp_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_005_small_basic_io_hello_world_cpp_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_006_small_basic_io_printf_check_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_007_small_basic_io_printf_check_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_008_small_basic_io_openat_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_009_small_basic_io_openat_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_010_small_basic_io_read_write_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_011_small_basic_io_read_write_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_012_small_basic_io_unlink_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_013_small_basic_io_unlink_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_014_small_basic_io_unlinkat_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_015_small_basic_io_unlinkat_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_016_small_basic_io_fread_fwrite_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_017_small_basic_io_fread_fwrite_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_018_small_basic_math_sqrt_double_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_019_small_basic_math_sqrt_double_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_020_small_basic_math_sqrt_float_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_021_small_basic_math_sqrt_float_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_022_small_basic_ops_test_branch_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_023_small_basic_ops_test_branch_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_024_small_basic_ops_test_shift_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_025_small_basic_ops_test_shift_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_026_small_misc_stream_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_027_small_misc_stream_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_028_small_misc_gettime_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_029_small_misc_gettime_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_030_small_misc_splitLoad_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_031_small_misc_splitLoad_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_032_small_misc_mt_dgemm_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_033_small_misc_mt_dgemm_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_034_small_misc_stream_fortran_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_035_small_misc_stream_fortran_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_036_small_misc_uname_mipsel_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_037_small_misc_uname_riscv64_</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_038_small_misc_fork_mipsel_gold1</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_039_small_misc_fork_mipsel_gold2</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_040_small_misc_fork_riscv64_gold1</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_041_small_misc_fork_riscv64_gold2</td>
    <td>SKIPPED</td>
  </tr>

  <tr>
    <td>test_vanadis_short_tests_042_small_misc_clone_mipsel_gold1</td>
    <td>SKIPPED</td>
  </tr>

  <t [...]

2024-05-10 19:38 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection is Not Necessary for this Pull Request.

2024-05-10 19:44 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1412</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1392</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1394</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 538</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 455</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 413</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 367</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 751</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 201</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (feldergast/sst-core)</dt>
  <ul>
    <li>Branch: checkpointing-serial</li>
    <li>SHA: abbbe258786b553efd3458ebc0f037fcb17487bf</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: d62858a7e10d5e30fd83571ecca643702efc7184</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: a637db3ef711b13f73de6fba08054ca344680be9</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0443cf578fcfd2fe8fe9ac3b039c3e16ba1f5892</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: feldergast
</details>
</details>

2024-05-10 20:59 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1412</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1392</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1394</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 538</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 455</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 413</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 367</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 751</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 201</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2024-05-10 20:59 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2024-05-10 21:00 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-05-10 21:19 UTC, jmlapre approved these changes
quick review

2024-05-10 21:48 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ jmlapre ]!

2024-05-10 21:49 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - Forked Repos cannot Automerge

2024-05-10 22:22 UTC, merged