Use and apply cmake-format
sstsimulator/sst-core pull request #963
Opened 2023-06-29 22:06 UTC by berquist

Closes #716

This uses `cmake-format` ([here](https://pypi.org/project/cmake-format/), [here](https://github.com/cheshirekow/cmakelang)) with its default settings to enforce CMake formatting.  The config was created to include help info for each setting, but it can be removed.

- There is a single commit (2ed33046eabe161bb62627b087d42a37a7113dbc) that applies these changes.  It is ignored in the relatively standardized `.git-blame-ignore-revs` so that blaming on GitHub and [the command line](https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame/#add-ignored-revisions-to-your-local-git-config) can skip these non-logic changes.
- It adds a `cmake-format-test.sh` that is equivalent to `clang-format-test.sh`.
- It adds a [GitHub Action](https://github.com/marketplace/actions/cmake-format-lint-action) workflow that works the same as the one for `clang-format`.

2023-06-29 22:17 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2023-06-29 22:19 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1070</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1054</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1056</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 433</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 355</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 313</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 267</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 412</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 100</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (berquist/sst-core)</dt>
  <ul>
    <li>Branch: 716-cmake-format</li>
    <li>SHA: d520a36278fd6661372b584b94f16e20221b7c45</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 85e037a1050c1dd8d3c56eabb231daa41c5be27d</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: ec7e7adb8cb42b2d2033fc12e416e2c12f905579</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 432426e6e6a709368feb9abc6f91c654ffad9b6f</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: berquist
</details>
</details>

2023-06-29 23:46 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1070</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1054</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1056</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 433</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 355</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 313</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 267</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 412</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 100</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2023-06-29 23:47 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

2023-06-29 23:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-06-30 04:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-06-30 08:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-06-30 12:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-06-30 13:47 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2023-06-30 13:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-06-30 18:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-06-30 22:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-01 02:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-01 07:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-01 11:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-01 15:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-01 20:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-02 00:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-02 05:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-02 09:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-02 14:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-02 18:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-02 22:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-03 02:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-03 06:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-03 11:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-03 15:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-03 19:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-04 00:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-04 04:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-04 12:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-04 16:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-04 21:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-05 01:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-05 06:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-05 10:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-05 14:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-05 18:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-05 23:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2023-07-05 23:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-07-06 00:44 UTC, jpkenny reviewed
I think it's better to fence the copyright statements so we don't have one format for cmake files and a different format for other files:

# ~~~
# This comment is fenced
#   and will not be formatted
# ~~~

2023-07-06 00:47 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

2023-07-06 00:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-07-06 00:48 UTC, jpkenny commented on .cmake-format.yaml
Probably better to make this a regular file in e.g. experimental/cmake and then explicitly invoke cmake-format with that regular file as an argument. More clear how it all works to the next developer that comes along that way.

2023-07-10 17:01 UTC, berquist commented
I saw there is also `--first-comment-is-literal` but I prefer the fences, otherwise you can keep adding comment lines to the top block and they won't be formatted.

2023-07-10 17:03 UTC, jpkenny commented
> I saw there is also `--first-comment-is-literal` but I prefer the fences, otherwise you can keep adding comment lines to the top block and they won't be formatted.

Agreed, I think fences are better.

2023-07-10 17:09 UTC, jpkenny requested changes
Everything besides the dot file looks good.

2023-07-10 17:17 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2023-07-10 17:19 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1077</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1061</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1063</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 434</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 356</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 314</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 268</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 419</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 101</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (berquist/sst-core)</dt>
  <ul>
    <li>Branch: 716-cmake-format</li>
    <li>SHA: b6d0e8e50a1da58b9af34fff4619bba4019dc596</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: c9a61a7948c282a6c20a13feb3f6cee95f8805da</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: bb0270fc3e8e1a65dfb6f8c779488c22a284b0d0</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 432426e6e6a709368feb9abc6f91c654ffad9b6f</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: berquist
</details>
</details>

2023-07-10 17:32 UTC, berquist commented on experimental/.cmake-format.yaml
Is there a reason why?  That makes it inconsistent with pretty much every other config file in SST and the world.

2023-07-10 17:44 UTC, jpkenny commented on experimental/.cmake-format.yaml
Avoid needlessly obscuring how things work. But .clang-format is already a dot file, so it's fine.

2023-07-10 17:45 UTC, jpkenny approved these changes
Thanks for the changes, looks good.

2023-07-10 18:24 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements</h3>
<ul>
  <li>Build Num: 1077</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MR-2</h3>
<ul>
  <li>Build Num: 1061</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-elements_MT-2</h3>
<ul>
  <li>Build Num: 1063</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 434</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core</h3>
<ul>
  <li>Build Num: 356</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.1.4_PY3.6_sst-core_Make-Dist</h3>
<ul>
  <li>Build Num: 314</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_Clang-Format_sst-core</h3>
<ul>
  <li>Build Num: 268</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-elements</h3>
<ul>
  <li>Build Num: 419</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-13.2-XC14-ARM_OMPI-4.1.4_PY3.10_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 101</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2023-07-10 18:24 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ jpkenny ]!

2023-07-10 18:24 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - Forked Repos cannot Automerge

2023-07-10 18:33 UTC, merged